FORMAT: 1A
HOST: http://weekendplanner.practo.com/

# WeekendPlanner

WeekendPlanner is a simple API allowing Practeons to view Weekend 
trips and join trips with others.

## Trips Collection [/trips]

### List All Trips [GET]
Gives all active upcoming trips.
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "avgCost": 900,
            "bookEndDate": 883679400000,
            "deleteStatus": "false",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883679400000,
            "totalPeople": 13,
            "travelBy": "Tempo Traveller",
            "vacancy": 4,
            "orgId": 1,
            "locationId": 1
          },
          {
            "id": 2,
            "avgCost": 1600,
            "bookEndDate": 883679400000,
            "deleteStatus": "true",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883634500000,
            "totalPeople": 5,
            "travelBy": "BMW -----X-----",
            "vacancy": 2,
            "orgId": 4,
            "locationId": 2
          }
        ]

### Create Trip [POST]
To Signup for Sepecific trip.

+ Request (application/json)

        {
            "avgCost": 900,
            "bookEndDate": 883679400000,
            "deleteStatus": "false",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "startDate": 883679400000,
            "totalPeople": 13,
            "travelBy": "Tempo Traveller",
            "vacancy": 4,
            "orgId": 1,
            "locationId": 1
        }

+ Response 201 (application/json)

    + Headers

            Location: /trips/1

    + Body

            {
            "id": 1,
            "avgCost": 900,
            "bookEndDate": 883679400000,
            "deleteStatus": "false",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883679400000,
            "totalPeople": 13,
            "travelBy": "Tempo Traveller",
            "vacancy": 4,
            "orgId": 1,
            "locationId": 1
            }

## Modification and Deletion of Trip [/mytrips/{trip_id}]

+ Parameters
    + trip_id (number) - ID of the trip

### Change Trip  [PUT]
Make Changes in the Trip Plan.

+ Request (application/json)

        {
            "id": 2,
            "avgCost": 1600,
            "bookEndDate": 883679400000,
            "deleteStatus": "true",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883634500000,
            "totalPeople": 5,
            "travelBy": "BMW -----X-----",
            "vacancy": 2,
            "orgId": 4,
            "locationId": 2
        }

+ Response 200 (application/json)

        {
            "id": 2,
            "avgCost": 1600,
            "bookEndDate": 883679400000,
            "deleteStatus": "true",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883634500000,
            "totalPeople": 5,
            "travelBy": "BMW -----X-----",
            "vacancy": 2,
            "orgId": 4,
            "locationId": 2
        }

### Delete [DELETE]
Deletes the Trip.

+ Response 204


## My Trips [/users/{id}/mytrips]

Trips that are organised or (Hosted) by the User.
+ Parameters
    + id (number) - ID of the trip

### Personal Trips [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "avgCost": 900,
            "bookEndDate": 883679400000,
            "deleteStatus": "false",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883679400000,
            "totalPeople": 13,
            "travelBy": "Tempo Traveller",
            "vacancy": 4,
            "orgId": 1,
            "locationId": 1
          },
          {
            "id": 2,
            "avgCost": 1600,
            "bookEndDate": 883679400000,
            "deleteStatus": "true",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883634500000,
            "totalPeople": 5,
            "travelBy": "BMW -----X-----",
            "vacancy": 2,
            "orgId": 1,
            "locationId": 2
          }
        ]

## Signed Trips [/users/{id}/ontrips]

Trips that are Signedup by the user.
+ Parameters
    + id (number) - ID of the trip

### Signedup Trips [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "avgCost": 900,
            "bookEndDate": 883679400000,
            "deleteStatus": "false",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883679400000,
            "totalPeople": 13,
            "travelBy": "Tempo Traveller",
            "vacancy": 4,
            "orgId": 1,
            "locationId": 1
          },
          {
            "id": 2,
            "avgCost": 1600,
            "bookEndDate": 883679400000,
            "deleteStatus": "true",
            "description": "View of Sunrise is really Good",
            "endDate": 883679400000,
            "modifyOn": 1471584952000,
            "startDate": 883634500000,
            "totalPeople": 5,
            "travelBy": "BMW -----X-----",
            "vacancy": 2,
            "orgId": 4,
            "locationId": 2
          }
        ]


## All Members in Trip [/trips/{id}/users]

All the practeons going to this Trip.
+ Parameters
    + id (number) - ID of the trip

### Trip Members [GET]
+ Response 200 (application/json)

        [
          {
            "id": 2,
            "email": "poornateja@practo.com",
            "mobile": "8985811049",
            "name": "poornateja"
          },
          {
            "id": 2,
            "email": "poornateja@practo.com",
            "mobile": "8985811049",
            "name": "poornateja"
          },
          {
            "id": 3,
            "email": "hello@practo.com",
            "mobile": "1234567890",
            "name": "hello"
          },
          {
            "id": 4,
            "email": "hello11@practo.com",
            "mobile": "1234567890",
            "name": "hello11"
          }
        ]

## Signup to Trip [/reltripuser/jointrip/{id}]

+ Parameters
    + id (number) - UserID of the trip
### Join Trip [POST]
+ Request (application/json)

        {
          "tripId": 1
          "deleteStatus": "false",
          "modifyById": 3
        }

+ Response 201 (application/json)

    + Headers

    + Body

            {
              "id": 2,
              "deleteStatus": "false",
              "modifyOn": 883679400000,
              "tripId": 1,
              "modifyById": 3,
              "userId": 3
            }
            
#All Users [/users]
All users in the database.

### Get all users [GET]
+ Response 200 (application/json)

        [
          {
            "id": 2,
            "email": "poornateja@practo.com",
            "mobile": "8985811049",
            "name": "poornateja"
          },
          {
            "id": 2,
            "email": "poornateja@practo.com",
            "mobile": "8985811049",
            "name": "poornateja"
          },
          {
            "id": 3,
            "email": "hello@practo.com",
            "mobile": "1234567890",
            "name": "hello"
          },
          {
            "id": 4,
            "email": "hello11@practo.com",
            "mobile": "1234567890",
            "name": "hello11"
          }
        ]

##Locations [/locations/all]
All Locations in Database.

### Get locations [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "name": "NandiHills",
            "type": "Hill Station"
          },
          {
            "id": 2,
            "name": "Kooorg",
            "type": "Seneric Place"
          },
          {
            "id": 3,
            "name": "NandiHills",
            "type": "Hill Station"
          }
        ]